---
title: "PERI - Matching of New material"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---
```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(tidyverse)
library(ggplot2)
library(stringi)
library(reshape2)
library(xlsx)
library(readxl)
library(shiny)
  
#Einlesen des ersten Stammdatensatzes und direktes selektieren und umbenennen der relevanten beiden Spalten:
master_data_art <- read_excel("C:\\Users\\Ritter\\Desktop\\Studium\\2018_Master\\190904_M10-Programming Languages\\03_Assignment\\Assignment_5_PERI_Project\\Datenquellen\\Schlüssel_Article_Stammdaten.xlsx")
master_data_art <- master_data_art[,c(2,7)]
names(master_data_art)[names(master_data_art)=="Art_No (neu+geb) Text"] <- "master_data_art_no"
names(master_data_art)[names(master_data_art)=="ArtNo_ArtBez Englisch"] <- "master_data_art_no_name"

# Einlesen des zweiten Stammdatensatzes und direktes selektieren und ausgeben der relevanten beiden Spalten:
master_data_PG <- read_excel("C:\\Users\\Ritter\\Desktop\\Studium\\2018_Master\\190904_M10-Programming Languages\\03_Assignment\\Assignment_5_PERI_Project\\Datenquellen\\Schlüssel_PG.xlsx")
master_data_PG <- master_data_PG[,c(1,5)]
names(master_data_PG)[names(master_data_PG)=="PG_Name English"] <- "PG_Name_English"
master_data_PG %>% colnames()

#Einlesen des dritten Stammdatensatzes und direktes selektieren und ausgeben der relevanten beiden Spalten:
master_data_MU <- read_excel("C:\\Users\\Ritter\\Desktop\\Studium\\2018_Master\\190904_M10-Programming Languages\\03_Assignment\\Assignment_5_PERI_Project\\Datenquellen\\Schlüssel_Land+MU.xlsx")
master_data_MU <- master_data_MU[,c(1,8)]
names(master_data_MU)[names(master_data_MU)=="Land_ID_Zahl...1"] <- "Country_Primary_Key"
names(master_data_MU)[names(master_data_MU)=="Market_Unit_Name...8"] <- "Market_Unit"
master_data_MU %>% colnames()

# Einlesen des vierten Datensatzes. Der Hauptdatensatensatz:
MIP_0 <- read_csv2("C:\\Users\\Ritter\\Desktop\\Studium\\2018_Master\\190904_M10-Programming Languages\\03_Assignment\\Assignment_5_PERI_Project\\Datenquellen\\MIP_FA0_20190919_DaniFranz.csv")

# Die Spaltennamen die mit "0_..." beginnen werden als allererste umbenannt, da R-Studio diese sonst im Ergänzungsvorschlag ungünstig einfügt:
names(MIP_0)[names(MIP_0)=="0_COUNTRY"] <- "COUNTRY_PRIMARY_KEY"
names(MIP_0)[names(MIP_0)=="0_COUNTRY_TEXT"] <- "COUNTRY"
names(MIP_0)[names(MIP_0)=="0_PG_NO"] <- "PG_NO"
names(MIP_0)[names(MIP_0)=="0_PG_NO_TEXT"] <- "PG_NO_TEXT"
names(MIP_0)[names(MIP_0)=="0_ARTANKEY"] <- "ARTANKEY"
names(MIP_0)[names(MIP_0)=="0_ARTICLE_NO_NEW"] <- "ARTICLE_NO_NEW"
names(MIP_0)[names(MIP_0)=="0_ARTICLE_NO_USED"] <- "ARTICLE_NO_USED"
names(MIP_0)[names(MIP_0)=="0_ARTICLE_NO_TEXT"] <- "ARTICLE_NO_TEXT"

# Nun werden fehlerhaft zugeordnete Datenformate der einzelnen Spalten korrigiert:
MIP_0$COUNTRY_PRIMARY_KEY <- as.character(MIP_0$COUNTRY_PRIMARY_KEY)
MIP_0$ARTICLE_NO_NEW <- as.character(MIP_0$ARTICLE_NO_NEW)
MIP_0$ARTICLE_NO_USED <- as.character(MIP_0$ARTICLE_NO_USED)
MIP_0$USED_QTY_TOTAL <- as.numeric(MIP_0$USED_QTY_TOTAL)

#In den nächsten Schritten könnnen die bereits eingelesenen Stammdatentabellen mit dem Hauptdatensatz verjoint werden:
MIP_0$ArticleNoId <- as.numeric(MIP_0$ARTICLE_NO_USED)
master_data_art$ArticleNoId <- as.numeric(master_data_art$master_data_art_no)
MIP_0 <-left_join(MIP_0, master_data_art)

MIP_0$PGNoId <- as.numeric(MIP_0$PG_NO)
master_data_PG$PGNoId <- as.numeric(master_data_PG$PG_No_Zahl)
MIP_0 <-left_join(MIP_0, master_data_PG)

MIP_0$Country_ID <- as.numeric(MIP_0$COUNTRY_PRIMARY_KEY)
master_data_MU$Country_ID <- as.numeric(master_data_MU$Country_Primary_Key)
MIP_0 <-left_join(MIP_0, master_data_MU)

# Datensatzreduktion
MIP_0 = MIP_0[,!grepl("LC",names(MIP_0))]
MIP_0 = MIP_0[,!grepl("FM",names(MIP_0))]
MIP_0 = MIP_0[,!grepl("LP1",names(MIP_0))]
MIP_0$master_data_art_no <- NULL
MIP_0$ArticleNoId <- NULL
MIP_0$PG_No_Zahl <- NULL
MIP_0$PG_NO_TEXT <- NULL
MIP_0$PGNoId <- NULL
MIP_0$Country_ID <- NULL
MIP_0$Country_Primary_Key <- NULL

#Umsortieren des Datensatzes
MIP_0 <- subset(MIP_0, select=c(33, 1:3,32,4:6,31,7:30))

#Datenanpassungen
#Auslastungswerte (also Mengen beim Kunden) in % auf der erste Nachkommastelle gerundet:
MIP_0$USED_UTIL_LTM <- round(MIP_0$USED_UTIL_LTM,1)
MIP_0$USED_UTIL_TODAY <-  round(MIP_0$USED_UTIL_TODAY,1)

#Da PERI mit sechsstelligen Artikelnummern arbeitet die Teilweise mit "0" und Teilweise mit "1 oder 2" beginnen, werden über folgenden Befehl die Artikelnummern mit fehlender führender Null angepasst:
MIP_0$ARTICLE_NO_NEW <- ifelse (nchar(MIP_0$ARTICLE_NO_NEW) == 5,paste0(0,MIP_0$ARTICLE_NO_NEW),MIP_0$ARTICLE_NO_NEW)

# NA-Handling

#Hinzufügen der landesspezifischen Artikelbezeichnungen im IsNa-Fall für Artikelnamen:
MIP_0$master_data_art_no_name <- ifelse (is.na(MIP_0$master_data_art_no_name), MIP_0$ARTICLE_NO_TEXT, MIP_0$master_data_art_no_name)

#Da die Masterdaten der Produktgruppen allumfassend sind, und IsNa für Produktgruppen auf landesspezifische, nicht relevante Produktgruppen schliepen lassen, werden die IsNa's der Produktgruppenbezeichnung einheitlich der Produktgruppe "Others" zugeordnet. 
MIP_0$PG_Name_English <- ifelse (is.na(MIP_0$PG_Name_English), "OTHERS", MIP_0$PG_Name_English)

#All diese Observations haben in irgendeiner Dataframespalte in einer/oder mehreren Wert-Variable Leerwerte. Diese NA Werte wurden fehlerhaft aus dem ERP-System von PERI ausgegeben. Um diese Datensätze für die weitere Analyse nicht zu verlieren, werden explizit die NA-Werte der Observations mit 0 ersetzt: -->
MIP_0[is.na(MIP_0)] <- 0
sum(is.na(MIP_0))

#Verketten der beiden Spalten PG_Nummer und PG_Name zur besseren Übersicht:
MIP_0$PG_Name_English <- str_c(MIP_0$PG_NO,"_",MIP_0$PG_Name_English)

## Parametisierung

#Damit der User weiss, welche Variablen in Frage kommen und um Eingabefehler zu vermeiden, werden die zunächst alle Möglichen String-Variablen des Datensatzes augegeben: -->
cat("Possible Selling Countries:\n ",paste(sort(unique(MIP_0$COUNTRY)),collapse=", "),"\n\n")
cat("Possible Receiving Market Units:\n ",paste(shQuote(sort(unique(MIP_0$Market_Unit)), type="sh"), collapse=", "))

#write.csv(MIP_0, "MIP_0_Interim_Result.csv")

# Erstellen eines Input Vectors für die Sidebar Optionen
Sub_Sell_Name <- as.vector(sort(unique(MIP_0$COUNTRY)))
Subs_Receiving <- as.vector(sort(unique(MIP_0$Market_Unit)))

```


Sidebar {.sidebar}
=====================================

Select the following Parameters:

```{r}
selectInput("select_name", label = "Select Selling Subsidiary:",
            choices = Sub_Sell_Name, selected = "Germany")

sliderInput("select_PG", label = "Select Product Groups:", min = 0, max = 99, value = c(0,99), dragRange = TRUE, sep="")

sliderInput("select_Sub_Sell_IC_MORE", label = "InventoryCoverage Seller higher than x-month:",
            min = 0.0, max = 10, value = 0, step = 0.5)

selectInput("select_Subs_Receiving", label = "Select Receiving Subsidiaries:",
            choices = Subs_Receiving, selected = "* no selection *", multiple = TRUE)

sliderInput("select_Subs_Rec_IC_Less", label = "InventoryCoverage Buyer lower than x-month:",
            min = 0.0, max = 10, value = 10, step = 0.5)
```

Overview
=====================================  


Row {data-height=650}
-------------------------------------

### Overivew Chart
```{r}
renderPlot({

Sub_Sell_PG_Pipe <- MIP_0 %>% mutate(PG_NO = as.integer(PG_NO)) %>% filter(PG_NO>=input$select_PG[1]&PG_NO<=input$select_PG[2])%>% distinct(PG_Name_English)

Sub_Sell_PG_Final <- paste0(Sub_Sell_PG_Pipe$PG_Name_English)

Sell_Articles <- MIP_0 %>% filter(COUNTRY == input$select_name, PG_Name_English %in% c(Sub_Sell_PG_Final),NEW_QTY_TOTAL>0, 
                NEW_INVENTORY_COVERAGE_TODAY >= input$select_Sub_Sell_IC_MORE) %>% 
                    select(c(PG_Name_English, ARTICLE_NO_NEW, master_data_art_no_name, NEW_QTY_TOTAL,
                    NEW_INVENTORY_COVERAGE_TODAY, NEW_AVG_DISPOSALS_LTM_PCS, NEW_TOTAL_EUR_LPT))

#Erstellen einer neuen Variable innerhalb des bereits bestehenden Datensatzes
Sell_Articles$Standard_vs_Local <- ifelse (as.integer(Sell_Articles$ARTICLE_NO_NEW) > 200000, "Local" , "Standard")

#Erstellen eines neuen Dataframes zur späteren möglichkeit der Analyse:
Sell_Articles_Std_vs_Local <- Sell_Articles %>% group_by(Standard_vs_Local) %>% summarise(
  Split_Value_LPT = sum(NEW_TOTAL_EUR_LPT),
  Split_Count_Articles= n()
  )
Sell_Articles_Std_vs_Local <- Sell_Articles_Std_vs_Local %>%  mutate(LPT_in_Percent = round(Split_Value_LPT/sum(Split_Value_LPT),3))


Sell_Articles_Std_vs_Local <- subset(Sell_Articles_Std_vs_Local, select= c(1,2,4,3))

#Wegfiltern lokaler Artikel im originären Datensatz
Sell_Articles <- Sell_Articles %>% filter(Standard_vs_Local == "Standard")

#important to be in this line, and not after renaming
Sell_Volume_LPT <- sum(Sell_Articles$NEW_TOTAL_EUR_LPT)
Sell_Volume_LPT2 <- paste(format(round(Sell_Volume_LPT / 1e3, 0), trim = TRUE), "tEUR")
Sell_Count_Art <- sum(complete.cases(Sell_Articles))

##Empfängerperspektive
  #Filtern des Gesamtdatensatzes
  Receiving_List_Total <- MIP_0 %>% 
    filter(Market_Unit == input$select_Subs_Receiving) %>% 
    filter(COUNTRY != input$select_name, NEW_INVENTORY_COVERAGE_TODAY < input$select_Subs_Rec_IC_Less) %>% 
    select(c(COUNTRY, ARTICLE_NO_NEW, ARTICLE_EUR_LPT, NEW_QTY_TOTAL, 
             NEW_TOTAL_EUR_LPT, NEW_INVENTORY_COVERAGE_TODAY, NEW_AVG_DISPOSALS_LTM_PCS))
  
  #Verknüpfen der Verkaufsmengen mit den Beständen in den potentiellen Käuferländern
  Receiving_List_Total <- right_join(Receiving_List_Total, Sell_Articles, by = "ARTICLE_NO_NEW", suffix = c("", ".sell"))
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Stück
  Receiving_List_Total$QTY_Calc <- Receiving_List_Total$NEW_QTY_TOTAL + Receiving_List_Total$NEW_QTY_TOTAL.sell
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Wert
  Receiving_List_Total$LPT_Calc <- Receiving_List_Total$QTY_Calc * Receiving_List_Total$ARTICLE_EUR_LPT
  
  #Berechnen einer theoretischen Inventory Coverage:
  Receiving_List_Total$IC_Calc <- Receiving_List_Total$QTY_Calc/Receiving_List_Total$NEW_AVG_DISPOSALS_LTM_PCS
   
  # Dummycodierung, wenn keine Abgänge in den LTM
  Receiving_List_Total$IC_Calc <- ifelse (is.infinite(Receiving_List_Total$IC_Calc), -1 , Receiving_List_Total$IC_Calc)
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Wert
  Receiving_List_Total$LPT_AVG_DispoEUR <- Receiving_List_Total$ARTICLE_EUR_LPT * Receiving_List_Total$NEW_AVG_DISPOSALS_LTM_PCS

  #Löschen von Zeilen, welche über den Right_Join des abgebenden Landes hinzugekommen sind:
  Receiving_List_Total <- Receiving_List_Total[!is.na(Receiving_List_Total$COUNTRY),]

# Pivot1
Receiving_IC <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, IC_Calc))

Receiving_IC <- spread(Receiving_IC, COUNTRY, IC_Calc)   #Pivotieren
colnames(Receiving_IC) <- paste(colnames(Receiving_IC), sep = "_","IC_Calc")    #Umbenennen der Spaltennamen
names(Receiving_IC)[names(Receiving_IC)=="ARTICLE_NO_NEW_IC_Calc"] <- "ARTICLE_NO_NEW"
Receiving_IC[is.na(Receiving_IC)] <- -2    #möglich aber nicht nötig

# Pivot2
Receiving_Value <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, NEW_TOTAL_EUR_LPT))
Receiving_Value <- spread(Receiving_Value, COUNTRY, NEW_TOTAL_EUR_LPT)   #Pivotieren
colnames(Receiving_Value) <- paste(colnames(Receiving_Value), sep = "_","LPT")    #Umbenennen der Spaltennamen
names(Receiving_Value)[names(Receiving_Value)=="ARTICLE_NO_NEW_LPT"] <- "ARTICLE_NO_NEW"
Receiving_Value[is.na(Receiving_Value)] <- 0  

# Pivot3
Receiving_QTY <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, NEW_QTY_TOTAL))
Receiving_QTY <- spread(Receiving_QTY, COUNTRY, NEW_QTY_TOTAL)   #Pivotieren
colnames(Receiving_QTY) <- paste(colnames(Receiving_QTY), sep = "_","QTY")    #Umbenennen der Spaltennamen
names(Receiving_QTY)[names(Receiving_QTY)=="ARTICLE_NO_NEW_QTY"] <- "ARTICLE_NO_NEW"
#Receiving_QTY[is.na(Receiving_QTY)] <- 0   #möglich aber nicht nötig
#Berechnung Gesamtsumme von Stück Bestand aus ALLEN abgebenden Ländern:
Receiving_QTY$Total_QTY_Rec <- rowSums(Receiving_QTY[,grep('_QTY', names(Receiving_QTY))], na.rm=TRUE)

# Umbenennen der Spalten auf Käuferseite
names(Sell_Articles)[names(Sell_Articles) == "master_data_art_no_name"] <- "Art_No+Name"
names(Sell_Articles)[names(Sell_Articles) == "NEW_QTY_TOTAL"] <- paste0(input$select_name,"_","NEW_QTY_TOTAL")
names(Sell_Articles)[names(Sell_Articles) == "NEW_INVENTORY_COVERAGE_TODAY"] <- paste0(input$select_name,"_","NEW_INVENTORY_COVERAGE_TODAY")
names(Sell_Articles)[names(Sell_Articles) == "NEW_TOTAL_EUR_LPT"] <- paste0(input$select_name,"_","NEW_TOTAL_EUR_LPT")
names(Sell_Articles)[names(Sell_Articles) == "NEW_AVG_DISPOSALS_LTM_PCS"] <- paste0(input$select_name,"_","NEW_AVG_DISPOSALS_LTM_PCS")


#Joins der Receiving_Datasets
  Selling_Match <- left_join(Receiving_IC, Receiving_Value, by = "ARTICLE_NO_NEW")
  Selling_Match <- left_join(Selling_Match, Receiving_QTY, by = "ARTICLE_NO_NEW")

##Umsortieren der Spalten - nach Rücksprache PERI nicht nötig.
    #names(Selling_Match)[names(Selling_Match)=="ARTICLE_NO_NEW"] <- "aaa_ARTICLE_NO_NEW"
    #Selling_Match <- Selling_Match[,order(colnames(Selling_Match))]
    #names(Selling_Match)[names(Selling_Match)=="aaa_ARTICLE_NO_NEW"] <- "ARTICLE_NO_NEW"

#Join zwischen Selling & Receiving Datasets
Selling_Match <-left_join(Sell_Articles, Selling_Match, by = "ARTICLE_NO_NEW")

#Ersetzen von is.na Werten, in Wertespalten (LPT) und Mengenspalten (QTY)
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_IC_Calc")), funs(replace_na(.,-11)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_LPT")), funs(replace_na(.,0)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_QTY")), funs(replace_na(.,0)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_QTY_Rec")), funs(replace_na(.,0)))

Purchasing_Match <- Receiving_List_Total %>% filter(-1 < IC_Calc, IC_Calc < input$select_Subs_Rec_IC_Less ) %>%  group_by(COUNTRY) %>%
                 summarise(LPT_EUR_before = sum(NEW_TOTAL_EUR_LPT), 
                           LPT_EUR_after = sum(LPT_Calc), 
                           LPT_EUR_Match = LPT_EUR_after - LPT_EUR_before, 
                           IC_before = round(LPT_EUR_before/sum(LPT_AVG_DispoEUR),2), 
                           IC_after = round(LPT_EUR_after/sum(LPT_AVG_DispoEUR),2),
                           y_pos_lab = LPT_EUR_before+(LPT_EUR_Match/2))
  Purchasing_Match$LPT_EUR_Match2 <- paste(format(round(Purchasing_Match$LPT_EUR_Match / 1e3, 0), trim = TRUE), "tEUR")  

###
  
ggplot(Purchasing_Match) +
        #Balkendiagramm
        geom_bar(aes(x=COUNTRY, y=LPT_EUR_after),stat="identity", fill = "#C0C0C0", col = "#C0C0C0", size = 1, alpha=0.7, marker ="test")+
        geom_bar(aes(x=COUNTRY, y=LPT_EUR_before),stat="identity", fill = "#FFC300", col = "#C0C0C0", size = 1, alpha=0.9)+
        
        geom_text(aes(label=LPT_EUR_Match2, x=COUNTRY, y=y_pos_lab), colour="Black")+
  
        #Punktdiagramm
        geom_point(aes(x=COUNTRY, y=IC_before*max(Purchasing_Match$LPT_EUR_after)/max(Purchasing_Match$IC_after)), 
                   stat="identity", shape=15, size = 4, col = "#FFC300")+
        geom_point(aes(x=COUNTRY, y=IC_after*max(Purchasing_Match$LPT_EUR_after)/max(Purchasing_Match$IC_after)), 
                    stat="identity", shape=17, size = 6, col = "#C0C0C0")+
         geom_text(aes(label=IC_before, x=COUNTRY, 
                        y=IC_before*max(Purchasing_Match$LPT_EUR_after)/max(Purchasing_Match$IC_after)),  size = 3, colour="Black")+
         geom_text(aes(label=IC_after, x=COUNTRY, 
                        y=IC_after*max(Purchasing_Match$LPT_EUR_after)/max(Purchasing_Match$IC_after)), size = 3, colour="Black")+
         
        #Sekundärachse
         scale_y_continuous(labels = scales::comma)+
         ylab("")+ 
        # labs(
        #     title = paste0(
        #       "Inventory matching from ",input$select_name, " to ", 
        #           paste0(shQuote(input$select_Subs_Receiving,type="sh"), collapse=", ")
        #       ),
        #     subtitle = paste0("Selloff Volume: ", input$select_name,": ", Sell_Volume_LPT2),
        #     x = "",
        #     y ="")+
        theme_bw()  
})

```

Row {data-height=250}
-------------------------------------

### Overview Table
```{r}
DT::renderDataTable({

Sub_Sell_PG_Pipe <- MIP_0 %>% mutate(PG_NO = as.integer(PG_NO)) %>% filter(PG_NO>=input$select_PG[1]&PG_NO<=input$select_PG[2])%>% distinct(PG_Name_English)

Sub_Sell_PG_Final <- paste0(Sub_Sell_PG_Pipe$PG_Name_English)

Sell_Articles <- MIP_0 %>% filter(COUNTRY == input$select_name, PG_Name_English %in% c(Sub_Sell_PG_Final),NEW_QTY_TOTAL>0, 
                NEW_INVENTORY_COVERAGE_TODAY >= input$select_Sub_Sell_IC_MORE) %>% 
                    select(c(PG_Name_English, ARTICLE_NO_NEW, master_data_art_no_name, NEW_QTY_TOTAL,
                    NEW_INVENTORY_COVERAGE_TODAY, NEW_AVG_DISPOSALS_LTM_PCS, NEW_TOTAL_EUR_LPT))
#Erstellen einer neuen Variable innerhalb des bereits bestehenden Datensatzes
Sell_Articles$Standard_vs_Local <- ifelse (as.integer(Sell_Articles$ARTICLE_NO_NEW) > 200000, "Local" , "Standard")

#Erstellen eines neuen Dataframes zur späteren möglichkeit der Analyse:
Sell_Articles_Std_vs_Local <- Sell_Articles %>% group_by(Standard_vs_Local) %>% summarise(
  Split_Value_LPT = sum(NEW_TOTAL_EUR_LPT),
  Split_Count_Articles= n()
  )
Sell_Articles_Std_vs_Local <- Sell_Articles_Std_vs_Local %>%  mutate(LPT_in_Percent = round(Split_Value_LPT/sum(Split_Value_LPT),3))


Sell_Articles_Std_vs_Local <- subset(Sell_Articles_Std_vs_Local, select= c(1,2,4,3))

#Wegfiltern lokaler Artikel im originären Datensatz
Sell_Articles <- Sell_Articles %>% filter(Standard_vs_Local == "Standard")

#important to be in this line, and not after renaming
Sell_Volume_LPT <- sum(Sell_Articles$NEW_TOTAL_EUR_LPT)
Sell_Volume_LPT2 <- paste(format(round(Sell_Volume_LPT / 1e3, 0), trim = TRUE), "tEUR")
Sell_Count_Art <- sum(complete.cases(Sell_Articles))

##Empfängerperspektive
  #Filtern des Gesamtdatensatzes
  Receiving_List_Total <- MIP_0 %>% 
    filter(Market_Unit == input$select_Subs_Receiving, COUNTRY != input$select_name, NEW_INVENTORY_COVERAGE_TODAY< input$select_Subs_Rec_IC_Less) %>% 
    select(c(COUNTRY, ARTICLE_NO_NEW, ARTICLE_EUR_LPT, NEW_QTY_TOTAL, 
             NEW_TOTAL_EUR_LPT, NEW_INVENTORY_COVERAGE_TODAY, NEW_AVG_DISPOSALS_LTM_PCS))
  
  #Verknüpfen der Verkaufsmengen mit den Beständen in den potentiellen Käuferländern
  Receiving_List_Total <- right_join(Receiving_List_Total, Sell_Articles, by = "ARTICLE_NO_NEW", suffix = c("", ".sell"))
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Stück
  Receiving_List_Total$QTY_Calc <- Receiving_List_Total$NEW_QTY_TOTAL + Receiving_List_Total$NEW_QTY_TOTAL.sell
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Wert
  Receiving_List_Total$LPT_Calc <- Receiving_List_Total$QTY_Calc * Receiving_List_Total$ARTICLE_EUR_LPT
  
  #Berechnen einer theoretischen Inventory Coverage:
  Receiving_List_Total$IC_Calc <- Receiving_List_Total$QTY_Calc/Receiving_List_Total$NEW_AVG_DISPOSALS_LTM_PCS
   
  # Dummycodierung, wenn keine Abgänge in den LTM
  Receiving_List_Total$IC_Calc <- ifelse (is.infinite(Receiving_List_Total$IC_Calc), -1 , Receiving_List_Total$IC_Calc)
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Wert
  Receiving_List_Total$LPT_AVG_DispoEUR <- Receiving_List_Total$ARTICLE_EUR_LPT * Receiving_List_Total$NEW_AVG_DISPOSALS_LTM_PCS

  #Löschen von Zeilen, welche über den Right_Join des abgebenden Landes hinzugekommen sind:
  Receiving_List_Total <- Receiving_List_Total[!is.na(Receiving_List_Total$COUNTRY),]

# Pivot1
Receiving_IC <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, IC_Calc))

Receiving_IC <- spread(Receiving_IC, COUNTRY, IC_Calc)   #Pivotieren
colnames(Receiving_IC) <- paste(colnames(Receiving_IC), sep = "_","IC_Calc")    #Umbenennen der Spaltennamen
names(Receiving_IC)[names(Receiving_IC)=="ARTICLE_NO_NEW_IC_Calc"] <- "ARTICLE_NO_NEW"
Receiving_IC[is.na(Receiving_IC)] <- -2    #möglich aber nicht nötig

# Pivot2
Receiving_Value <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, NEW_TOTAL_EUR_LPT))
Receiving_Value <- spread(Receiving_Value, COUNTRY, NEW_TOTAL_EUR_LPT)   #Pivotieren
colnames(Receiving_Value) <- paste(colnames(Receiving_Value), sep = "_","LPT")    #Umbenennen der Spaltennamen
names(Receiving_Value)[names(Receiving_Value)=="ARTICLE_NO_NEW_LPT"] <- "ARTICLE_NO_NEW"
Receiving_Value[is.na(Receiving_Value)] <- 0  

# Pivot3
Receiving_QTY <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, NEW_QTY_TOTAL))
Receiving_QTY <- spread(Receiving_QTY, COUNTRY, NEW_QTY_TOTAL)   #Pivotieren
colnames(Receiving_QTY) <- paste(colnames(Receiving_QTY), sep = "_","QTY")    #Umbenennen der Spaltennamen
names(Receiving_QTY)[names(Receiving_QTY)=="ARTICLE_NO_NEW_QTY"] <- "ARTICLE_NO_NEW"
#Receiving_QTY[is.na(Receiving_QTY)] <- 0   #möglich aber nicht nötig
#Berechnung Gesamtsumme von Stück Bestand aus ALLEN abgebenden Ländern:
Receiving_QTY$Total_QTY_Rec <- rowSums(Receiving_QTY[,grep('_QTY', names(Receiving_QTY))], na.rm=TRUE)

# Umbenennen der Spalten auf Käuferseite
names(Sell_Articles)[names(Sell_Articles) == "master_data_art_no_name"] <- "Art_No+Name"
names(Sell_Articles)[names(Sell_Articles) == "NEW_QTY_TOTAL"] <- paste0(input$select_name,"_","NEW_QTY_TOTAL")
names(Sell_Articles)[names(Sell_Articles) == "NEW_INVENTORY_COVERAGE_TODAY"] <- paste0(input$select_name,"_","NEW_INVENTORY_COVERAGE_TODAY")
names(Sell_Articles)[names(Sell_Articles) == "NEW_TOTAL_EUR_LPT"] <- paste0(input$select_name,"_","NEW_TOTAL_EUR_LPT")
names(Sell_Articles)[names(Sell_Articles) == "NEW_AVG_DISPOSALS_LTM_PCS"] <- paste0(input$select_name,"_","NEW_AVG_DISPOSALS_LTM_PCS")


#Joins der Receiving_Datasets
  Selling_Match <- full_join(Receiving_IC, Receiving_Value, by = "ARTICLE_NO_NEW")
  Selling_Match <- full_join(Selling_Match, Receiving_QTY, by = "ARTICLE_NO_NEW")

##Umsortieren der Spalten - nach Rücksprache PERI nicht nötig.
    #names(Selling_Match)[names(Selling_Match)=="ARTICLE_NO_NEW"] <- "aaa_ARTICLE_NO_NEW"
    #Selling_Match <- Selling_Match[,order(colnames(Selling_Match))]
    #names(Selling_Match)[names(Selling_Match)=="aaa_ARTICLE_NO_NEW"] <- "ARTICLE_NO_NEW"

#Join zwischen Selling & Receiving Datasets
Selling_Match <-left_join(Sell_Articles, Selling_Match, by = "ARTICLE_NO_NEW")

#Ersetzen von is.na Werten, in Wertespalten (LPT) und Mengenspalten (QTY)
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_IC_Calc")), funs(replace_na(.,-11)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_LPT")), funs(replace_na(.,0)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_QTY")), funs(replace_na(.,0)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_QTY_Rec")), funs(replace_na(.,0)))

Purchasing_Match <- Receiving_List_Total %>% filter(-1 < IC_Calc, IC_Calc < input$select_Subs_Rec_IC_Less ) %>%  group_by(COUNTRY) %>%
                 summarise(LPT_EUR_before = sum(NEW_TOTAL_EUR_LPT), 
                           LPT_EUR_after = sum(LPT_Calc), 
                           LPT_EUR_Match = LPT_EUR_after - LPT_EUR_before, 
                           IC_before_Month = round(LPT_EUR_before/sum(LPT_AVG_DispoEUR),2), 
                           IC_after_Month = round(LPT_EUR_after/sum(LPT_AVG_DispoEUR),2))
Purchasing_Match  

datatable(Purchasing_Match) %>% formatCurrency(2:4, "\U20AC", before = FALSE, digits = 0, dec.mark =",", interval = 3, mark = ".")

},

server=FALSE,
rownames= FALSE,
class = 'cell-border compact stripe order-column',

options = list(
    scrollX= TRUE,
    scrollY= TRUE,
    pageLength = 5,
    fixedHeader = TRUE,
    dom = 't',
    columnDefs = list(list(className = 'dt-right', targets = c(1,2,3)))
    )
)
```

Detailed table
=====================================     
   
### Detailed table
```{r}

DT::renderDataTable({

Sub_Sell_PG_Pipe <- MIP_0 %>% mutate(PG_NO = as.integer(PG_NO)) %>% filter(PG_NO>=input$select_PG[1]&PG_NO<=input$select_PG[2])%>% distinct(PG_Name_English)

Sub_Sell_PG_Final <- paste0(Sub_Sell_PG_Pipe$PG_Name_English)

Sell_Articles <- MIP_0 %>% filter(COUNTRY == input$select_name, PG_Name_English %in% c(Sub_Sell_PG_Final),NEW_QTY_TOTAL>0, 
                NEW_INVENTORY_COVERAGE_TODAY >= input$select_Sub_Sell_IC_MORE) %>% 
                    select(c(PG_Name_English, ARTICLE_NO_NEW, master_data_art_no_name, NEW_QTY_TOTAL,
                    NEW_INVENTORY_COVERAGE_TODAY, NEW_AVG_DISPOSALS_LTM_PCS, NEW_TOTAL_EUR_LPT))
#Erstellen einer neuen Variable innerhalb des bereits bestehenden Datensatzes
Sell_Articles$Standard_vs_Local <- ifelse (as.integer(Sell_Articles$ARTICLE_NO_NEW) > 200000, "Local" , "Standard")

#Erstellen eines neuen Dataframes zur späteren möglichkeit der Analyse:
Sell_Articles_Std_vs_Local <- Sell_Articles %>% group_by(Standard_vs_Local) %>% summarise(
  Split_Value_LPT = sum(NEW_TOTAL_EUR_LPT),
  Split_Count_Articles= n()
  )
Sell_Articles_Std_vs_Local <- Sell_Articles_Std_vs_Local %>%  mutate(LPT_in_Percent = round(Split_Value_LPT/sum(Split_Value_LPT),3))


Sell_Articles_Std_vs_Local <- subset(Sell_Articles_Std_vs_Local, select= c(1,2,4,3))

#Wegfiltern lokaler Artikel im originären Datensatz
Sell_Articles <- Sell_Articles %>% filter(Standard_vs_Local == "Standard")

#important to be in this line, and not after renaming
Sell_Volume_LPT <- sum(Sell_Articles$NEW_TOTAL_EUR_LPT)
Sell_Volume_LPT2 <- paste(format(round(Sell_Volume_LPT / 1e3, 0), trim = TRUE), "tEUR")
Sell_Count_Art <- sum(complete.cases(Sell_Articles))

##Empfängerperspektive
  #Filtern des Gesamtdatensatzes
  Receiving_List_Total <- MIP_0 %>% 
    filter(Market_Unit == input$select_Subs_Receiving, COUNTRY != input$select_name, NEW_INVENTORY_COVERAGE_TODAY< input$select_Subs_Rec_IC_Less) %>% 
    select(c(COUNTRY, ARTICLE_NO_NEW, ARTICLE_EUR_LPT, NEW_QTY_TOTAL, 
             NEW_TOTAL_EUR_LPT, NEW_INVENTORY_COVERAGE_TODAY, NEW_AVG_DISPOSALS_LTM_PCS))
  
  #Verknüpfen der Verkaufsmengen mit den Beständen in den potentiellen Käuferländern
  Receiving_List_Total <- right_join(Receiving_List_Total, Sell_Articles, by = "ARTICLE_NO_NEW", suffix = c("", ".sell"))
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Stück
  Receiving_List_Total$QTY_Calc <- Receiving_List_Total$NEW_QTY_TOTAL + Receiving_List_Total$NEW_QTY_TOTAL.sell
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Wert
  Receiving_List_Total$LPT_Calc <- Receiving_List_Total$QTY_Calc * Receiving_List_Total$ARTICLE_EUR_LPT
  
  #Berechnen einer theoretischen Inventory Coverage:
  Receiving_List_Total$IC_Calc <- Receiving_List_Total$QTY_Calc/Receiving_List_Total$NEW_AVG_DISPOSALS_LTM_PCS
   
  # Dummycodierung, wenn keine Abgänge in den LTM
  Receiving_List_Total$IC_Calc <- ifelse (is.infinite(Receiving_List_Total$IC_Calc), -1 , Receiving_List_Total$IC_Calc)
  
  #Berechnen des theoretischen neuen Bestandes im Käuferland in Wert
  Receiving_List_Total$LPT_AVG_DispoEUR <- Receiving_List_Total$ARTICLE_EUR_LPT * Receiving_List_Total$NEW_AVG_DISPOSALS_LTM_PCS

  #Löschen von Zeilen, welche über den Right_Join des abgebenden Landes hinzugekommen sind:
  Receiving_List_Total <- Receiving_List_Total[!is.na(Receiving_List_Total$COUNTRY),]

# Pivot1
Receiving_IC <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, IC_Calc))

Receiving_IC <- spread(Receiving_IC, COUNTRY, IC_Calc)   #Pivotieren
colnames(Receiving_IC) <- paste(colnames(Receiving_IC), sep = "_","IC_Calc")    #Umbenennen der Spaltennamen
names(Receiving_IC)[names(Receiving_IC)=="ARTICLE_NO_NEW_IC_Calc"] <- "ARTICLE_NO_NEW"
Receiving_IC[is.na(Receiving_IC)] <- -2    #möglich aber nicht nötig

# Pivot2
Receiving_Value <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, NEW_TOTAL_EUR_LPT))
Receiving_Value <- spread(Receiving_Value, COUNTRY, NEW_TOTAL_EUR_LPT)   #Pivotieren
colnames(Receiving_Value) <- paste(colnames(Receiving_Value), sep = "_","LPT")    #Umbenennen der Spaltennamen
names(Receiving_Value)[names(Receiving_Value)=="ARTICLE_NO_NEW_LPT"] <- "ARTICLE_NO_NEW"
Receiving_Value[is.na(Receiving_Value)] <- 0  

# Pivot3
Receiving_QTY <- Receiving_List_Total %>% select(c(COUNTRY, ARTICLE_NO_NEW, NEW_QTY_TOTAL))
Receiving_QTY <- spread(Receiving_QTY, COUNTRY, NEW_QTY_TOTAL)   #Pivotieren
colnames(Receiving_QTY) <- paste(colnames(Receiving_QTY), sep = "_","QTY")    #Umbenennen der Spaltennamen
names(Receiving_QTY)[names(Receiving_QTY)=="ARTICLE_NO_NEW_QTY"] <- "ARTICLE_NO_NEW"
#Receiving_QTY[is.na(Receiving_QTY)] <- 0   #möglich aber nicht nötig
#Berechnung Gesamtsumme von Stück Bestand aus ALLEN abgebenden Ländern:
Receiving_QTY$Total_QTY_Rec <- rowSums(Receiving_QTY[,grep('_QTY', names(Receiving_QTY))], na.rm=TRUE)

# Umbenennen der Spalten auf Käuferseite
names(Sell_Articles)[names(Sell_Articles) == "master_data_art_no_name"] <- "Art_No+Name"
names(Sell_Articles)[names(Sell_Articles) == "NEW_QTY_TOTAL"] <- paste0(input$select_name,"_","NEW_QTY_TOTAL")
names(Sell_Articles)[names(Sell_Articles) == "NEW_INVENTORY_COVERAGE_TODAY"] <- paste0(input$select_name,"_","NEW_INVENTORY_COVERAGE_TODAY")
names(Sell_Articles)[names(Sell_Articles) == "NEW_TOTAL_EUR_LPT"] <- paste0(input$select_name,"_","NEW_TOTAL_EUR_LPT")
names(Sell_Articles)[names(Sell_Articles) == "NEW_AVG_DISPOSALS_LTM_PCS"] <- paste0(input$select_name,"_","NEW_AVG_DISPOSALS_LTM_PCS")


#Joins der Receiving_Datasets
  Selling_Match <- full_join(Receiving_IC, Receiving_Value, by = "ARTICLE_NO_NEW")
  Selling_Match <- full_join(Selling_Match, Receiving_QTY, by = "ARTICLE_NO_NEW")

##Umsortieren der Spalten - nach Rücksprache PERI nicht nötig.
#    names(Selling_Match)[names(Selling_Match)=="ARTICLE_NO_NEW"] <- "aaa_ARTICLE_NO_NEW"
#    Selling_Match <- Selling_Match[,order(colnames(Selling_Match))]
#    names(Selling_Match)[names(Selling_Match)=="aaa_ARTICLE_NO_NEW"] <- "ARTICLE_NO_NEW"

#Join zwischen Selling & Receiving Datasets
Selling_Match <-left_join(Sell_Articles, Selling_Match, by = "ARTICLE_NO_NEW")

#Ersetzen von is.na Werten, in Wertespalten (LPT) und Mengenspalten (QTY)
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_IC_Calc")), funs(replace_na(.,-11)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_LPT")), funs(replace_na(.,0)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_QTY")), funs(replace_na(.,0)))
  Selling_Match <- Selling_Match %>% mutate_at(vars(ends_with("_QTY_Rec")), funs(replace_na(.,0)))

  Selling_Match <- select(Selling_Match, -c(ARTICLE_NO_NEW,Standard_vs_Local)) 
  
},  

server=FALSE,
rownames= FALSE,
class = 'cell-border compact stripe order-column',
#caption = "PERI - detailled inventory analysis",
extensions = c('Buttons', 'FixedColumns', 'KeyTable'), 
options = list(
    scrollX= TRUE,
    scrollY= TRUE,
    pageLength = 10,
    fixedColumns = list(leftColumns = 2),
    dom = 'Bfrtip',
    buttons = c('csv', 'excel', "colvis"),
    keys = TRUE
    )
)
```